// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipcMessage.proto

package ets.genielog.appwatcher_3.profiling.ipc;

public final class IpcMessage {
  private IpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Profiling.ipc.ipcAction}
   */
  public enum ipcAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OS = 1;</code>
     *
     * <pre>
     ** OS 
     * </pre>
     */
    OS(0, 1),
    /**
     * <code>CPU = 2;</code>
     *
     * <pre>
     ** CPU 
     * </pre>
     */
    CPU(1, 2),
    /**
     * <code>PROCESS = 3;</code>
     *
     * <pre>
     ** Process 
     * </pre>
     */
    PROCESS(2, 3),
    /**
     * <code>NETWORK = 4;</code>
     *
     * <pre>
     ** Network 
     * </pre>
     */
    NETWORK(3, 4),
    /**
     * <code>KILLPROCESS = 5;</code>
     *
     * <pre>
     ** Kill Processes 
     * </pre>
     */
    KILLPROCESS(4, 5),
    ;

    /**
     * <code>OS = 1;</code>
     *
     * <pre>
     ** OS 
     * </pre>
     */
    public static final int OS_VALUE = 1;
    /**
     * <code>CPU = 2;</code>
     *
     * <pre>
     ** CPU 
     * </pre>
     */
    public static final int CPU_VALUE = 2;
    /**
     * <code>PROCESS = 3;</code>
     *
     * <pre>
     ** Process 
     * </pre>
     */
    public static final int PROCESS_VALUE = 3;
    /**
     * <code>NETWORK = 4;</code>
     *
     * <pre>
     ** Network 
     * </pre>
     */
    public static final int NETWORK_VALUE = 4;
    /**
     * <code>KILLPROCESS = 5;</code>
     *
     * <pre>
     ** Kill Processes 
     * </pre>
     */
    public static final int KILLPROCESS_VALUE = 5;


    public final int getNumber() { return value; }

    public static ipcAction valueOf(int value) {
      switch (value) {
        case 1: return OS;
        case 2: return CPU;
        case 3: return PROCESS;
        case 4: return NETWORK;
        case 5: return KILLPROCESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ipcAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ipcAction>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ipcAction>() {
            public ipcAction findValueByNumber(int number) {
              return ipcAction.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final ipcAction[] VALUES = values();

    public static ipcAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ipcAction(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Profiling.ipc.ipcAction)
  }

  public interface ipcDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Profiling.ipc.ipcAction action = 1;
    /**
     * <code>required .Profiling.ipc.ipcAction action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required .Profiling.ipc.ipcAction action = 1;</code>
     */
    ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction getAction();

    // repeated bytes payload = 2;
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getPayloadList();
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    int getPayloadCount();
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload(int index);
  }
  /**
   * Protobuf type {@code Profiling.ipc.ipcData}
   */
  public static final class ipcData extends
      com.google.protobuf.GeneratedMessage
      implements ipcDataOrBuilder {
    // Use ipcData.newBuilder() to construct.
    private ipcData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ipcData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ipcData defaultInstance;
    public static ipcData getDefaultInstance() {
      return defaultInstance;
    }

    public ipcData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ipcData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction value = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              payload_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.class, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder.class);
    }

    public static com.google.protobuf.Parser<ipcData> PARSER =
        new com.google.protobuf.AbstractParser<ipcData>() {
      public ipcData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ipcData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ipcData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Profiling.ipc.ipcAction action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction action_;
    /**
     * <code>required .Profiling.ipc.ipcAction action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Profiling.ipc.ipcAction action = 1;</code>
     */
    public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction getAction() {
      return action_;
    }

    // repeated bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> payload_;
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getPayloadList() {
      return payload_;
    }
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload(int index) {
      return payload_.get(index);
    }

    private void initFields() {
      action_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction.OS;
      payload_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      for (int i = 0; i < payload_.size(); i++) {
        output.writeBytes(2, payload_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < payload_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(payload_.get(i));
        }
        size += dataSize;
        size += 1 * getPayloadList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Profiling.ipc.ipcData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.class, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder.class);
      }

      // Construct using Profiling.ipc.IpcMessage.ipcData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction.OS;
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_descriptor;
      }

      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData getDefaultInstanceForType() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.getDefaultInstance();
      }

      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData build() {
        ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData buildPartial() {
        ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData result = new ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData) {
          return mergeFrom((ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData other) {
        if (other == ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Profiling.ipc.ipcAction action = 1;
      private ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction action_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction.OS;
      /**
       * <code>required .Profiling.ipc.ipcAction action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Profiling.ipc.ipcAction action = 1;</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction getAction() {
        return action_;
      }
      /**
       * <code>required .Profiling.ipc.ipcAction action = 1;</code>
       */
      public Builder setAction(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Profiling.ipc.ipcAction action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcAction.OS;
        onChanged();
        return this;
      }

      // repeated bytes payload = 2;
      private java.util.List<com.google.protobuf.ByteString> payload_ = java.util.Collections.emptyList();
      private void ensurePayloadIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          payload_ = new java.util.ArrayList<com.google.protobuf.ByteString>(payload_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPayloadList() {
        return java.util.Collections.unmodifiableList(payload_);
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public int getPayloadCount() {
        return payload_.size();
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload(int index) {
        return payload_.get(index);
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder setPayload(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder addPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder addAllPayload(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePayloadIsMutable();
        super.addAll(values, payload_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Profiling.ipc.ipcData)
    }

    static {
      defaultInstance = new ipcData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Profiling.ipc.ipcData)
  }

  public interface ipcMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];
    /**
     * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
     */
    boolean hasType();
    /**
     * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
     */
    ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType getType();

    // repeated .Profiling.ipc.ipcData data = 2;
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    java.util.List<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData> 
        getDataList();
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData getData(int index);
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    java.util.List<? extends ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Profiling.ipc.ipcMessage}
   */
  public static final class ipcMessage extends
      com.google.protobuf.GeneratedMessage
      implements ipcMessageOrBuilder {
    // Use ipcMessage.newBuilder() to construct.
    private ipcMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ipcMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ipcMessage defaultInstance;
    public static ipcMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ipcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ipcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType value = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readMessage(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.class, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ipcMessage> PARSER =
        new com.google.protobuf.AbstractParser<ipcMessage>() {
      public ipcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ipcMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ipcMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Profiling.ipc.ipcMessage.ipcType}
     */
    public enum ipcType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACTION = 0;</code>
       *
       * <pre>
       ** ACTION 
       * </pre>
       */
      ACTION(0, 0),
      /**
       * <code>RESULT = 1;</code>
       *
       * <pre>
       ** RESULT 
       * </pre>
       */
      RESULT(1, 1),
      /**
       * <code>COMMAND = 2;</code>
       *
       * <pre>
       ** COMMAND 
       * </pre>
       */
      COMMAND(2, 2),
      /**
       * <code>EXIT = 10;</code>
       *
       * <pre>
       ** EXIT 
       * </pre>
       */
      EXIT(3, 10),
      ;

      /**
       * <code>ACTION = 0;</code>
       *
       * <pre>
       ** ACTION 
       * </pre>
       */
      public static final int ACTION_VALUE = 0;
      /**
       * <code>RESULT = 1;</code>
       *
       * <pre>
       ** RESULT 
       * </pre>
       */
      public static final int RESULT_VALUE = 1;
      /**
       * <code>COMMAND = 2;</code>
       *
       * <pre>
       ** COMMAND 
       * </pre>
       */
      public static final int COMMAND_VALUE = 2;
      /**
       * <code>EXIT = 10;</code>
       *
       * <pre>
       ** EXIT 
       * </pre>
       */
      public static final int EXIT_VALUE = 10;


      public final int getNumber() { return value; }

      public static ipcType valueOf(int value) {
        switch (value) {
          case 0: return ACTION;
          case 1: return RESULT;
          case 2: return COMMAND;
          case 10: return EXIT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ipcType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ipcType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ipcType>() {
              public ipcType findValueByNumber(int number) {
                return ipcType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ipcType[] VALUES = values();

      public static ipcType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ipcType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Profiling.ipc.ipcMessage.ipcType)
    }

    private int bitField0_;
    // required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];
    public static final int TYPE_FIELD_NUMBER = 1;
    private ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType type_;
    /**
     * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
     */
    public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType getType() {
      return type_;
    }

    // repeated .Profiling.ipc.ipcData data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData> data_;
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    public java.util.List<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    public java.util.List<? extends ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
     */
    public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      type_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType.ACTION;
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Profiling.ipc.ipcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.class, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.Builder.class);
      }

      // Construct using Profiling.ipc.IpcMessage.ipcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType.ACTION;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_descriptor;
      }

      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage getDefaultInstanceForType() {
        return ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.getDefaultInstance();
      }

      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage build() {
        ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage buildPartial() {
        ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage result = new ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage) {
          return mergeFrom((ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage other) {
        if (other == ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];
      private ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType type_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType.ACTION;
      /**
       * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType getType() {
        return type_;
      }
      /**
       * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
       */
      public Builder setType(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Profiling.ipc.ipcMessage.ipcType type = 1 [default = ACTION];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcMessage.ipcType.ACTION;
        onChanged();
        return this;
      }

      // repeated .Profiling.ipc.ipcData data = 2;
      private java.util.List<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData>(data_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder> dataBuilder_;

      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public java.util.List<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder setData(
          int index, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder setData(
          int index, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder addData(ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder addData(
          int index, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder addData(
          ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder addData(
          int index, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public java.util.List<? extends ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.getDefaultInstance());
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.getDefaultInstance());
      }
      /**
       * <code>repeated .Profiling.ipc.ipcData data = 2;</code>
       */
      public java.util.List<ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcData.Builder, ets.genielog.appwatcher_3.profiling.ipc.IpcMessage.ipcDataOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Profiling.ipc.ipcMessage)
    }

    static {
      defaultInstance = new ipcMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Profiling.ipc.ipcMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ipcMessage.proto\022\'ets.genielog.appwatc" +
      "her_3.profiling.ipc\"^\n\007ipcData\022B\n\006action" +
      "\030\001 \002(\01622.Profi" +
      "ling.ipc.ipcAction\022\017\n\007payload\030\002 \003(\014\"\331\001\n\n" +
      "ipcMessage\022Q\n\004type\030\001 \002(\0162;.ets.genielog." +
      "appwatcher_3.profiling.ipc.ipcMessage.ip" +
      "cType:\006ACTION\022>\n\004data\030\002 \003(\01320.ets.geniel" +
      "og.appwatcher_3.profiling.ipc.ipcData\"8\n" +
      "\007ipcType\022\n\n\006ACTION\020\000\022\n\n\006RESULT\020\001\022\013\n\007COMM" +
      "AND\020\002\022\010\n\004EXIT\020\n*G\n\tipcAction\022\006\n\002OS\020\001\022\007\n\003",
      "CPU\020\002\022\013\n\007PROCESS\020\003\022\013\n\007NETWORK\020\004\022\017\n\013KILLP" +
      "ROCESS\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcData_descriptor,
              new java.lang.String[] { "Action", "Payload", });
          internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ets_genielog_appwatcher_3_profiling_ipc_ipcMessage_descriptor,
              new java.lang.String[] { "Type", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
