// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: networkInfo.proto

#ifndef PROTOBUF_networkInfo_2eproto__INCLUDED
#define PROTOBUF_networkInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ets {
namespace genielog {
namespace appwatcher_3 {
namespace profiling {
namespace core {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_networkInfo_2eproto();
void protobuf_AssignDesc_networkInfo_2eproto();
void protobuf_ShutdownFile_networkInfo_2eproto();

class networkInfo;

// ===================================================================

class networkInfo : public ::google::protobuf::Message {
 public:
  networkInfo();
  virtual ~networkInfo();

  networkInfo(const networkInfo& from);

  inline networkInfo& operator=(const networkInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const networkInfo& default_instance();

  void Swap(networkInfo* other);

  // implements Message ----------------------------------------------

  networkInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const networkInfo& from);
  void MergeFrom(const networkInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required uint32 flags = 2;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 2;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ets.genielog.appwatcher_3.profiling.core.model.networkInfo)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_flags();
  inline void clear_has_flags();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::uint32 flags_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_networkInfo_2eproto();
  friend void protobuf_AssignDesc_networkInfo_2eproto();
  friend void protobuf_ShutdownFile_networkInfo_2eproto();

  void InitAsDefaultInstance();
  static networkInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// networkInfo

// required string name = 1;
inline bool networkInfo::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void networkInfo::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void networkInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void networkInfo::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& networkInfo::name() const {
  return *name_;
}
inline void networkInfo::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void networkInfo::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void networkInfo::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* networkInfo::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* networkInfo::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void networkInfo::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 flags = 2;
inline bool networkInfo::has_flags() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void networkInfo::set_has_flags() {
  _has_bits_[0] |= 0x00000002u;
}
inline void networkInfo::clear_has_flags() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void networkInfo::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 networkInfo::flags() const {
  return flags_;
}
inline void networkInfo::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace profiling
}  // namespace appwatcher_3
}  // namespace genielog
}  // namespace ets

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_networkInfo_2eproto__INCLUDED
