// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "processInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ets {
namespace genielog {
namespace appwatcher_3 {
namespace profiling {
namespace core {

namespace {

const ::google::protobuf::Descriptor* processInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  processInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_processInfo_2eproto() {
  protobuf_AddDesc_processInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "processInfo.proto");
  GOOGLE_CHECK(file != NULL);
  processInfo_descriptor_ = file->message_type(0);
  static const int processInfo_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, pid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, cpuusage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, cputime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, prioritylevel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, usedusertime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, usedsystemtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, rss_),
  };
  processInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      processInfo_descriptor_,
      processInfo::default_instance_,
      processInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(processInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(processInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_processInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    processInfo_descriptor_, &processInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_processInfo_2eproto() {
  delete processInfo::default_instance_;
  delete processInfo_reflection_;
}

void protobuf_AddDesc_processInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021processInfo.proto\022(ets.genielog.appwat"
    "cher_3.profiling.core\"\252\001\n\013processInfo\022\014\n"
    "\004name\030\001 \002(\t\022\013\n\003uid\030\002 \002(\r\022\013\n\003pid\030\003 \002(\r\022\020\n"
    "\010cpuUsage\030\004 \002(\002\022\017\n\007cpuTime\030\005 \002(\004\022\025\n\rprio"
    "rityLevel\030\006 \002(\r\022\024\n\014usedUserTime\030\007 \002(\004\022\026\n"
    "\016usedSystemTime\030\010 \002(\004\022\013\n\003rss\030\t \002(\004", 234);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "processInfo.proto", &protobuf_RegisterTypes);
  processInfo::default_instance_ = new processInfo();
  processInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_processInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_processInfo_2eproto {
  StaticDescriptorInitializer_processInfo_2eproto() {
    protobuf_AddDesc_processInfo_2eproto();
  }
} static_descriptor_initializer_processInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int processInfo::kNameFieldNumber;
const int processInfo::kUidFieldNumber;
const int processInfo::kPidFieldNumber;
const int processInfo::kCpuUsageFieldNumber;
const int processInfo::kCpuTimeFieldNumber;
const int processInfo::kPriorityLevelFieldNumber;
const int processInfo::kUsedUserTimeFieldNumber;
const int processInfo::kUsedSystemTimeFieldNumber;
const int processInfo::kRssFieldNumber;
#endif  // !_MSC_VER

processInfo::processInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void processInfo::InitAsDefaultInstance() {
}

processInfo::processInfo(const processInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void processInfo::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  uid_ = 0u;
  pid_ = 0u;
  cpuusage_ = 0;
  cputime_ = GOOGLE_ULONGLONG(0);
  prioritylevel_ = 0u;
  usedusertime_ = GOOGLE_ULONGLONG(0);
  usedsystemtime_ = GOOGLE_ULONGLONG(0);
  rss_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

processInfo::~processInfo() {
  SharedDtor();
}

void processInfo::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void processInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* processInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return processInfo_descriptor_;
}

const processInfo& processInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_processInfo_2eproto();
  return *default_instance_;
}

processInfo* processInfo::default_instance_ = NULL;

processInfo* processInfo::New() const {
  return new processInfo;
}

void processInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    uid_ = 0u;
    pid_ = 0u;
    cpuusage_ = 0;
    cputime_ = GOOGLE_ULONGLONG(0);
    prioritylevel_ = 0u;
    usedusertime_ = GOOGLE_ULONGLONG(0);
    usedsystemtime_ = GOOGLE_ULONGLONG(0);
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    rss_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool processInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_uid;
        break;
      }

      // required uint32 uid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_pid;
        break;
      }

      // required uint32 pid = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_pid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pid_)));
          set_has_pid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_cpuUsage;
        break;
      }

      // required float cpuUsage = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_cpuUsage:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &cpuusage_)));
          set_has_cpuusage();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_cpuTime;
        break;
      }

      // required uint64 cpuTime = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cpuTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &cputime_)));
          set_has_cputime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_priorityLevel;
        break;
      }

      // required uint32 priorityLevel = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_priorityLevel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &prioritylevel_)));
          set_has_prioritylevel();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_usedUserTime;
        break;
      }

      // required uint64 usedUserTime = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_usedUserTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &usedusertime_)));
          set_has_usedusertime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_usedSystemTime;
        break;
      }

      // required uint64 usedSystemTime = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_usedSystemTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &usedsystemtime_)));
          set_has_usedsystemtime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_rss;
        break;
      }

      // required uint64 rss = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_rss:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &rss_)));
          set_has_rss();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void processInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // required uint32 uid = 2;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->uid(), output);
  }

  // required uint32 pid = 3;
  if (has_pid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->pid(), output);
  }

  // required float cpuUsage = 4;
  if (has_cpuusage()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->cpuusage(), output);
  }

  // required uint64 cpuTime = 5;
  if (has_cputime()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->cputime(), output);
  }

  // required uint32 priorityLevel = 6;
  if (has_prioritylevel()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->prioritylevel(), output);
  }

  // required uint64 usedUserTime = 7;
  if (has_usedusertime()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(7, this->usedusertime(), output);
  }

  // required uint64 usedSystemTime = 8;
  if (has_usedsystemtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(8, this->usedsystemtime(), output);
  }

  // required uint64 rss = 9;
  if (has_rss()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(9, this->rss(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* processInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required uint32 uid = 2;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->uid(), target);
  }

  // required uint32 pid = 3;
  if (has_pid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->pid(), target);
  }

  // required float cpuUsage = 4;
  if (has_cpuusage()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->cpuusage(), target);
  }

  // required uint64 cpuTime = 5;
  if (has_cputime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->cputime(), target);
  }

  // required uint32 priorityLevel = 6;
  if (has_prioritylevel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->prioritylevel(), target);
  }

  // required uint64 usedUserTime = 7;
  if (has_usedusertime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(7, this->usedusertime(), target);
  }

  // required uint64 usedSystemTime = 8;
  if (has_usedsystemtime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(8, this->usedsystemtime(), target);
  }

  // required uint64 rss = 9;
  if (has_rss()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(9, this->rss(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int processInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required uint32 uid = 2;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->uid());
    }

    // required uint32 pid = 3;
    if (has_pid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->pid());
    }

    // required float cpuUsage = 4;
    if (has_cpuusage()) {
      total_size += 1 + 4;
    }

    // required uint64 cpuTime = 5;
    if (has_cputime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->cputime());
    }

    // required uint32 priorityLevel = 6;
    if (has_prioritylevel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->prioritylevel());
    }

    // required uint64 usedUserTime = 7;
    if (has_usedusertime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->usedusertime());
    }

    // required uint64 usedSystemTime = 8;
    if (has_usedsystemtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->usedsystemtime());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required uint64 rss = 9;
    if (has_rss()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->rss());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void processInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const processInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const processInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void processInfo::MergeFrom(const processInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_pid()) {
      set_pid(from.pid());
    }
    if (from.has_cpuusage()) {
      set_cpuusage(from.cpuusage());
    }
    if (from.has_cputime()) {
      set_cputime(from.cputime());
    }
    if (from.has_prioritylevel()) {
      set_prioritylevel(from.prioritylevel());
    }
    if (from.has_usedusertime()) {
      set_usedusertime(from.usedusertime());
    }
    if (from.has_usedsystemtime()) {
      set_usedsystemtime(from.usedsystemtime());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_rss()) {
      set_rss(from.rss());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void processInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void processInfo::CopyFrom(const processInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool processInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x000001ff) != 0x000001ff) return false;

  return true;
}

void processInfo::Swap(processInfo* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(uid_, other->uid_);
    std::swap(pid_, other->pid_);
    std::swap(cpuusage_, other->cpuusage_);
    std::swap(cputime_, other->cputime_);
    std::swap(prioritylevel_, other->prioritylevel_);
    std::swap(usedusertime_, other->usedusertime_);
    std::swap(usedsystemtime_, other->usedsystemtime_);
    std::swap(rss_, other->rss_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata processInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = processInfo_descriptor_;
  metadata.reflection = processInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace profiling
}  // namespace appwatcher_3
}  // namespace genielog
}  // namespace ets

// @@protoc_insertion_point(global_scope)
